### ISSUE TITLE
Iterator functions

### ISSUE THREAD

**Issue by sobolevn** [amka/dictator#1]
I have stumbled upon your library and I really liked it. But saw this:

> .iterkeys()
> .itervalues()
> .iteritems()

That's the way `python2` deals with things. But `python3` does create generators by default. And that's how I suppose the things should be. When you need a `list` you can create it with `list(some.items())`.

What do you think of it? Will it affect performance? Will it make the API more native for `python3` users?

PS: Do you support both `python2` and `python3`? Or maybe I will create a new issue for it.

**Comment by amka** [comment]
Thanks for comment. At the moment I've made it for Python2 but I'll review how it should work in version 3 and comment back soon.
