### ISSUE TITLE
python version support

### ISSUE THREAD

**Issue by sobolevn** [amka/dictator#2]
As I have mentioned in #1, I have a question about python versions support. I did not find any sign of it neither in readme nor `setup.py`.

By the way, you have your `classifiers` missing in the `setup.py`. I can help with that. Should I create a PR with this?

And badge with versions is also a good thing to have. I love badges.

**Comment by amka** [comment]
I also love badges and have to add this to readme, definitely.
And it will be great if you make a PR. Thanks
