### ISSUE TITLE
get the proper datatype

### ISSUE THREAD

**Issue by sobolevn** [amka/dictator#4]
It would be nice to have this functionality out-of-the box: http://stackoverflow.com/questions/13060632/getting-values-with-the-right-type-in-redis

What do you think? For now if you add line `[1, 2, 3]` [here](https://github.com/sobolevn/dictator/blob/81a613bbd3403fb56c55c347fb8c0dd7b346a455/tests/conftest.py#L16), it would break. As the return value would be: `['1', '2', '3']`.

**Comment by amka** [comment]
Unfortunately, Redis saves data inside as Strings or lists of String or sets. So it always lose type's metadata when we put variables to it.
I thought about how to store metadata and return exactly the same values as they were saved to storage, but all of these options should store additional data to Redis and cause to decreased performance.

So for current moment I don't see how to change this situation.
