### ISSUE TITLE
Is it still maintained?

### ISSUE THREAD

**Issue by sobolevn** [amka/dictator#6]
Do you have any plans on maintaining this project?

If not, do you consider any options on donating it? 
[We](https://github.com/wemake-services) will actually use it. But firstly upgrade it to `python3`.

**Comment by amka** [comment]
Hey. Yup, I currently use it in my own project  but there is not much activity on this repo so it won't be a necessary change. 
After your words of course I will update it to python 3.

**Comment by amka** [comment]
Updated to Python 3. Tested on 3.5, 3.6.
